#!/bin/bash

PP=$(dirname $0)
[ -f $PP/conf.ini ] || $PP/config
[ -f $PP/conf.ini ] || exit -1
. $PP/conf.ini	

if [ -z "$1" ] || [ -z "$2" ]
then
	echo Usage: ./run.sh MODEL CASE.xml [gpus]
	exit -1
fi

CASE=$2
TIME=$4

NUMCASES=$( cat $CASE | wc -l )

echo "Detected $NUMCASES cases"

MODEL=$1
GPUS=$3
TIME=0:30:00

if [ -z "$GPUS" ]
then
	GPUS=1
fi

if [ ! -f "$CASE" ]
then
	echo No case file: $CASE
	exit -1
fi

NAME=CLB:$CASE
NCPU=$GPUS

SOLVER=$TCLB/CLB/$MODEL/main

if [ ! -f "$SOLVER" ]
then
	echo No such model: $MODEL
	echo File not found: $SOLVER
	exit -1
fi



sbatch <<EOF
#!/bin/bash -l
#SBATCH -J $NAME
#SBATCH -N 1
#SBATCH -n $NCPU
#SBATCH --time=$TIME 
#SBATCH -A $GRANT
#SBATCH -p plgrid-short
#SBATCH --array=1-$NUMCASES
 
     cd \$SLURM_SUBMIT_DIR 
echo "###### Nodes:          #######"
     srun --ntasks-per-node=1 /bin/hostname
echo "###### Loading modules #######"
     module load tools/openmpi
     module load apps/cuda
echo "###### --------------- #######"
echo ""
     acase=\$(cat $CASE | head -n \$SLURM_ARRAY_TASK_ID | tail -n 1)
     cd \$(dirname \$acase)
     echo \$(pwd)
     mpirun $SOLVER \$(basename \$acase)
EOF
