#!/bin/bash

PP=$(dirname $0)
[ -f $PP/conf.ini ] || $PP/config
[ -f $PP/conf.ini ] || exit -1
. $PP/conf.ini	

if [ -z "$1" ] || [ -z "$2" ]
then
	echo Usage: ./run.sh MODEL CASE.xml [gpus]
	exit -1
fi

CASE=$2
TIME=$4

NUMCASES=$( cat $CASE | wc -l )

echo "Detected $NUMCASES cases"

MODEL=$1
GPUS=$3

if [[  "x$5" == "x" ]]
then
    AOK=""
else
    AOK="#SBATCH  --depend=afterany:$5"
fi 


if [ -z "$GPUS" ]
then
	GPUS=1
fi

echo Trying to run $CASE with $MODEL model on $GPUS gpus...

if [ $GPUS -gt 1 ]
then
	PPN=2
	NODES=$[$GPUS/2]
else
	PPN=1
	NODES=1
fi

if [ $GPUS -ne $[$NODES*$PPN] ]
then
	echo Requested number of GPUS \($GPUS\) is not $NODES x $PPN
	exit -1
fi

if [ ! -f "$CASE" ]
then
	echo No case file: $CASE
	exit -1
fi

NAME=CLB:$CASE
NCPU=$GPUS

SOLVER=$TCLB/CLB/$MODEL/main

if [ ! -f "$SOLVER" ]
then
	echo No such model: $MODEL
	echo File not found: $SOLVER
	exit -1
fi



sbatch <<EOF
#!/bin/bash -l
#SBATCH -J $NAME
#SBATCH -N $NODES
#SBATCH -n $NCPU
#SBATCH --ntasks-per-node=$PPN
#SBATCH --time=$TIME 
#SBATCH -A $GRANT
#SBATCH -p plgrid-gpu
#SBATCH --gres=gpu:$PPN
#SBATCH --array=1-$NUMCASES
$AOK
     cd \$SLURM_SUBMIT_DIR
     pwd 
echo "###### Nodes:          #######"
     srun --ntasks-per-node=1 /bin/hostname
echo "###### nVidia-SMI:     #######"
     nvidia-smi
echo "###### Loading modules #######"

	module load plgrid/apps/r/3.4.4
	module load plgrid/tools/openmpi/2.1.1-gcc-6.4.0
	module load plgrid/apps/cuda/9.0
	module load plgrid/libs/python-numpy/1.14.2-python-2.7


echo "###### --------------- #######"
echo ""
     acase=\$(cat $CASE | head -n \$SLURM_ARRAY_TASK_ID | tail -n 1)
     cd \$(dirname \$acase)
     mpirun $SOLVER \$(basename \$acase)
     if test \$SLURM_ARRAY_TASK_ID -ge $(cat $CASE | wc -l)
     then
         pb_msg 'Array job finished'
     fi
EOF
